numbers = [1, 5,2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers.append(20)
print(numbers)
numbers.insert(4,14)
print(numbers)
numbers.remove(2)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(8))
print(40 in numbers)
print(numbers.count(5))
print(numbers.sort())
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
print(numbers2)
numbers.append(19)
print(numbers2)